FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS build

USER 0
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-122:latest

COPY --from=build /app/dist /opt/app-root/src
COPY nginx.conf /opt/app-root/etc/nginx.default.d/triforce.conf

USER 1001
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
