{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: {{ .Values.namespace }}
  labels:
    app: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: {{ .Values.kafka.image }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              rpk redpanda start \
                --mode dev-container \
                --smp 1 \
                --memory 512M \
                --default-log-level=warn \
                --overprovisioned
          ports:
            - containerPort: 9092
              name: kafka
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["rpk", "cluster", "health"]
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: redpanda
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
{{- end }}
