apiVersion: v1
kind: Secret
metadata:
  name: triforce-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  litellm-api-base: {{ .Values.litellm.apiBase | quote }}
  litellm-api-key: {{ .Values.litellm.apiKey | quote }}
  postgres-user: {{ .Values.postgres.user | quote }}
  postgres-password: {{ required "postgres password required" .Values.postgres.password | quote }}
