apiVersion: v1
kind: Namespace
metadata:
  name: triforce
  labels:
    app.kubernetes.io/part-of: triforce
    intel.com/hardware: xeon-6767p
---
apiVersion: v1
kind: Secret
metadata:
  name: triforce-secrets
  namespace: triforce
type: Opaque
stringData:
  postgres-user: triforce
  postgres-password: triforce-oberon-2026
  litellm-api-key: local-oberon-key
