apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
spec:
  annotations:
    sidecar.istio.io/inject: "false"
  supportedModelFormats:
    - name: vLLM
      autoSelect: true
  multiModel: false
  containers:
    - name: kserve-container
      image: quay.io/modh/vllm:rhoai-2.16
      args:
        - --model=/mnt/models
        - --port=8080
        - --dtype=auto
        - --max-model-len=2048
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: "4"
          memory: 4Gi
        limits:
          cpu: "8"
          memory: 8Gi
