---
ocp4_workload_gitops_bootstrap_health_ignore: true

__meta__:
  deployer:
    scm_ref: main

  sandboxes:
    - kind: OcpSandbox
      cloud_selector:
        purpose: dev
        cloud: cnv-dedicated-shared
        lab: ai-qs-intel-inference
