#!/bin/bash
# Triforce Preflight Report — runs all validation stages and outputs Markdown
# Usage: ./scripts/preflight-report.sh [output-file]
# Default output: tests/preflight-report.md

set -o pipefail

REPORT="${1:-tests/preflight-report.md}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
CLUSTER=$(KUBECONFIG=~/.kube/config-oberon oc whoami --show-server 2>/dev/null || echo "unknown")
NODE=$(KUBECONFIG=~/.kube/config-oberon oc get nodes -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "unknown")

TOTAL_PASS=0
TOTAL_FAIL=0
TOTAL_SKIP=0
STAGES=""

run_stage() {
  local num="$1"
  local name="$2"
  local cmd="$3"

  echo "Running stage $num: $name..." >&2
  local output
  output=$(eval "$cmd" 2>&1)
  local exit_code=$?

  local passed=$(echo "$output" | grep -oE '[0-9]+ passed' | head -1 | grep -oE '[0-9]+' || echo "0")
  local failed=$(echo "$output" | grep -oE '[0-9]+ failed' | head -1 | grep -oE '[0-9]+' || echo "0")
  local skipped=$(echo "$output" | grep -oE '[0-9]+ skipped' | head -1 | grep -oE '[0-9]+' || echo "0")
  local duration=$(echo "$output" | grep -oE 'in [0-9.]+s' | tail -1 || echo "")

  if [ "$passed" = "0" ] && [ "$failed" = "0" ]; then
    if [ $exit_code -eq 0 ]; then
      passed="OK"
      failed="0"
    else
      passed="0"
      failed="1"
    fi
  fi

  TOTAL_PASS=$((TOTAL_PASS + ${passed//OK/1}))
  TOTAL_FAIL=$((TOTAL_FAIL + failed))
  TOTAL_SKIP=$((TOTAL_SKIP + skipped))

  local status="GREEN"
  [ "$failed" != "0" ] && status="RED"

  STAGES="$STAGES| $num | $name | $passed | $failed | $skipped | **$status** | $duration |\n"

  # Capture failures for detail section
  if [ "$failed" != "0" ]; then
    echo "" >> /tmp/preflight-failures.txt
    echo "### Stage $num: $name — FAILURES" >> /tmp/preflight-failures.txt
    echo '```' >> /tmp/preflight-failures.txt
    echo "$output" | grep "FAILED\|AssertionError\|Error" | head -10 >> /tmp/preflight-failures.txt
    echo '```' >> /tmp/preflight-failures.txt
  fi
}

# Clear failures file
> /tmp/preflight-failures.txt

# Run stages
run_stage 1 "Contracts (Stage 0)" \
  "python3 -m pytest tests/contracts/ --tb=no -q 2>&1"

run_stage 2 "Unit Tests (Stage 2)" \
  "python3 -m pytest services/healthcare-agent/tests/ --tb=no -q 2>&1"

run_stage 3 "Modules (Stage 8)" \
  "python3 -m pytest tests/test_stage_8_modules.py --tb=no -q 2>&1"

run_stage 4 "Frontend Build" \
  "cd frontend && npm run build 2>&1 && echo '1 passed'"

run_stage 5 "Helm Lint" \
  "helm template infrastructure/helm --set postgres.password=test --set litellm.apiKey=test --set litellm.apiBase=http://test > /dev/null 2>&1 && helm template infrastructure/helm -f infrastructure/oberon/values-oberon.yaml > /dev/null 2>&1 && echo '2 passed'"

run_stage 6 "Deployment (D0-D10)" \
  "KUBECONFIG=~/.kube/config-oberon python3 -m pytest tests/test_deployment.py --tb=no -q -k 'not frontend_builds' 2>&1"

run_stage 7 "Edge + Virt (V0-V4)" \
  "KUBECONFIG=~/.kube/config-oberon python3 -m pytest tests/test_virt_edge.py --tb=no -q -k 'not frontend_builds' 2>&1"

run_stage 8 "Claims + Isolation" \
  "KUBECONFIG=~/.kube/config-oberon python3 -m pytest tests/test_claim_accuracy.py tests/test_demo_isolation.py --tb=no -q 2>&1"

# Claims audit
UNVERIFIED=$(python3 -c "import yaml; d=yaml.safe_load(open('tests/claim_registry.yaml')); u=[c for c in d['claims'] if not c.get('verified')]; print(len(u))" 2>/dev/null || echo "?")
VERIFIED=$(python3 -c "import yaml; d=yaml.safe_load(open('tests/claim_registry.yaml')); v=[c for c in d['claims'] if c.get('verified')]; print(len(v))" 2>/dev/null || echo "?")
TOTAL_CLAIMS=$(python3 -c "import yaml; d=yaml.safe_load(open('tests/claim_registry.yaml')); print(len(d['claims']))" 2>/dev/null || echo "?")

# Generate report
cat > "$REPORT" << EOF
# Triforce Preflight Report

**Generated:** $TIMESTAMP
**Cluster:** $CLUSTER
**Node:** $NODE

## Summary

| Metric | Value |
|---|---|
| Total Passed | **$TOTAL_PASS** |
| Total Failed | **$TOTAL_FAIL** |
| Total Skipped | $TOTAL_SKIP |
| Overall | $([ $TOTAL_FAIL -eq 0 ] && echo "**ALL GREEN**" || echo "**$TOTAL_FAIL FAILURES**") |

## Stages

| # | Stage | Passed | Failed | Skipped | Status | Duration |
|---|---|---|---|---|---|---|
$(echo -e "$STAGES")

## Claims Audit

| Metric | Value |
|---|---|
| Total Claims | $TOTAL_CLAIMS |
| Verified | $VERIFIED |
| Unverified | $UNVERIFIED |

### Unverified Claims
$(python3 -c "
import yaml
d = yaml.safe_load(open('tests/claim_registry.yaml'))
for c in d['claims']:
    if not c.get('verified'):
        print(f'- **{c[\"id\"]}**: {c[\"value\"]} — {c.get(\"notes\", \"\")}')" 2>/dev/null || echo "Could not read registry")

$(cat /tmp/preflight-failures.txt 2>/dev/null)

---
*Generated by \`scripts/preflight-report.sh\`*
EOF

echo "Report written to: $REPORT" >&2
echo "" >&2
echo "Summary: $TOTAL_PASS passed, $TOTAL_FAIL failed, $TOTAL_SKIP skipped" >&2
[ $TOTAL_FAIL -eq 0 ] && echo "STATUS: ALL GREEN" >&2 || echo "STATUS: $TOTAL_FAIL FAILURES" >&2
